#!/bin/bash -x
#!/bin/bash
export PS4='(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

function grub {
	local grubdir
	local localedir
	local dir

	grubdir=/tftpboot/grub
	localedir=/usr/share/locale

	cp -t "${grubdir}"/ grub.pxe

	# Copy gettext files
	mkdir -p "${grubdir}"/locale/
	for dir in "${localedir}"/*; do
	    	if test -f "$dir/LC_MESSAGES/grub.mo"; then
			cp -f "$dir/LC_MESSAGES/grub.mo" "${grubdir}/locale/${dir##*/}.mo"
	    	fi
	done

	# i386-coreboot
	# i386-multiboot
	# i386-pc
	# i386-qemu
	# mipsel-yeeloong-flash
	# mipsel-yeeloong-elf
	# i386-ieee1275
	# powerpc-ieee1275
	# sparc64-ieee1275-raw
	# sparc64-ieee1275-aout
}

function bs_test {
	ls debian-installer/*/boot-screens/*.cfg debian-installer/*/boot-screens/*/*.cfg | grep txt | sed -e 's!^\(.*\)\(txt\)\(.*\)$!mv -i \1\2\3 \1gtk\3!e' -e '/^$/d'
}

function download_arch {
	local mirror
	local release
	local version
	local arch
	local quiet

	mirror="$1";shift
	release="$1";shift
	version="$1";shift
	arch="$1";shift

	quiet=''
	#quiet='--no-check-certificate'
	#quiet='--no-check-certificate -nv'

	case "$arch" in
		kfreebsd-*)
			wget $quiet -p -x -nH --cut-dirs="$(echo "${mirror}"|awk -F/ '{print NF}')" -P debian-installer/"${release}" -i - << EOF
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/netboot/netboot.tar.gz
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/netboot/gtk/netboot.tar.gz

			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/netboot-9/netboot.tar.gz
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/netboot-9/gtk/netboot.tar.gz
EOF
		#	${mirror}/dists/${release}/main/installer-${arch}/${version}/images/netboot-10/netboot.tar.gz
		#	${mirror}/dists/${release}/main/installer-${arch}/${version}/images/netboot-10/gtk/netboot.tar.gz
			;;
		i386|amd64)
			wget $quiet -p -x -nH --cut-dirs="$(echo "${mirror}"|awk -F/ '{print NF}')" -P debian-installer/"${release}" -i - << EOF
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/netboot/netboot.tar.gz
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/netboot/gtk/netboot.tar.gz
EOF
			;;
		powerpc)
			wget $quiet -p -x -nH --cut-dirs="$(echo "${mirror}///"|awk -F/ '{print NF}')" -P debian-installer/"${release}" -i - << EOF
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc/netboot/boot.msg
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc/netboot/initrd.gz
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc/netboot/mini.iso
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc/netboot/vmlinux
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc/netboot/vmlinuz-chrp.initrd
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc/netboot/yaboot
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc/netboot/yaboot.conf
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc/netboot/gtk/initrd.gz
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc/netboot/gtk/mini.iso
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc/netboot/gtk/vmlinux

			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc64/netboot/boot.msg
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc64/netboot/initrd.gz
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc64/netboot/mini.iso
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc64/netboot/vmlinux
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc64/netboot/vmlinuz-chrp.initrd
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc64/netboot/yaboot
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc64/netboot/yaboot.conf
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc64/netboot/gtk/initrd.gz
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc64/netboot/gtk/mini.iso
			${mirror}/dists/${release}/main/installer-${arch}/${version}/images/powerpc64/netboot/gtk/vmlinux
EOF
			;;
	esac
}

function download {
	local mirror
	local release
	local version
	local arch
	local quiet

	mirror="$1";shift
	release="$1";shift
	version="$1";shift

	for arch do
		download_arch "${mirror}" "${release}" "${version}" "${arch}"
	done
}

function move {
	local release
	local version


	release="$1";shift
	version="$1";shift

	[ -d debian-installer ]&&find debian-installer \! -type d -print0|\
	sed -zr \
		-e 's!^(debian-installer/'"${release}"'/installer-)([^/]*/)('"${version}"'/images/netboot[-0-9]*/)(netboot.tar.gz)$!mkdir -p '"${version}-${release}"'/\2tmp/txt\&\&mv -i "&" '"${version}-${release}"'/\2tmp/txt/\4!e' \
		-e 's!^(debian-installer/'"${release}"'/installer-)([^/]*/)('"${version}"'/images/netboot[-0-9]*/)(gtk/netboot.tar.gz)$!mkdir -p '"${version}-${release}"'/\2tmp/gtk\&\&mv -i "&" '"${version}-${release}/\2tmp/\4!e" \
		-e 's!^(debian-installer/'"${release}"'/)([^/]*/)(netboot[-0-9]*/)(gtk/)([^/]*)$!mkdir -p '"${version}-${release}"'/\2\&\&mv -i "&" '"${version}-${release}/\2gtk-\5!e" \
		-e 's!^(debian-installer/'"${release}"'/)([^/]*/)(netboot[-0-9]*/)(vmlinux|mini.iso|initrd.gz)$!mkdir -p '"${version}-${release}"'/\2\&\&mv -i "&" '"${version}-${release}/\2txt-\4!e" \
		-e 's!^(debian-installer/'"${release}"'/)([^/]*/)(netboot[-0-9]*/)([^/]*)$!mkdir -p '"${version}-${release}"'/\2\&\&mv -i "&" '"${version}-${release}/\2\4!e" \
		-e '/^$/d' |xargs -0rn1 \
	&& echo ok

	find "${version}-${release}" \! -type d -print0|\
	sed -nzr \
		-e "s!^(${version}-${release}"'/[^/]*/tmp/)(txt/|gtk/)(netboot.tar.gz)$!cd \1\2\&\&tar -xzf \3 \&\& rm \3!ep' |\
	sed -zr \
		-e '/^$/d' |xargs -0rn1 \
	&& echo ok

	find "${version}-${release}" \! -type d -print0|\
	sed -z\
		-e "s!^\(${version}-${release}"''"/\)\([^/]*\)\(/tmp/\)\(txt/\|gtk/\)\(debian-installer/\)\2\(/boot-screens/\)\([^/]*\)\$!set -x;if [ \! -e \"\1\2\6\7\" ] ; then mkdir -p \1\2\6 \&\& mv -it \1\2\6 \1\2\3\4\5\2\6\7 ; elif diff -u \1\2\6\7 \1\2\3\4\5\2\6\7 ; then rm \1\2\3\4\5\2\6\7 ; fi!e" \
		-e "s!^\(${version}-${release}"''"/\)\([^/]*\)\(/tmp/\)\(txt/\|gtk/\)\(debian-installer/\)\2\(/grub/\)\([^/]*\)\$!set -x;if [ \! -e \"\1\2\6\7\" ] ; then mkdir -p \1\2\6 \&\& mv -it \1\2\6 \1\2\3\4\5\2\6\7 ; elif diff -u \1\2\6\7 \1\2\3\4\5\2\6\7 ; then rm \1\2\3\4\5\2\6\7 ; fi!e" \
		-e "s!^\(${version}-${release}"''"/\)\([^/]*\)\(/tmp/\)\(txt/\|gtk/\)\(debian-installer/\)\2\(/grub/[x864_]*-efi/\)\([^/]*\)\$!if [ \! -e \"\1\2\6\7\" ] ; then mkdir -p \1\2\6 \&\& mv -it \1\2\6 \1\2\3\4\5\2\6\7 ; elif diff -u \1\2\6\7 \1\2\3\4\5\2\6\7 ; then rm \1\2\3\4\5\2\6\7 ; fi!e" \
		-e "s!^\(${version}-${release}"''"/\)\([^/]*\)\(/tmp/\)\(txt/\|gtk/\)\(debian-installer/\)\2\(/pxelinux.cfg/\)\([^/]*\)\$!if [ -L \1\2\3\4\5\2\6\7 ] ; then rm \1\2\3\4\5\2\6\7 ; elif [ \! -e \"\1\2\6\7\" ] ; then mkdir -p \1\2\6 \&\& mv -it \1\2\6 \1\2\3\4\5\2\6\7 ; elif diff -u \1\2\6\7 \1\2\3\4\5\2\6\7 ; then rm \1\2\3\4\5\2\6\7 ; fi!e" \
		-e "s!^\(${version}-${release}"''"/\)\([^/]*\)\(/tmp/\)\(txt\|gtk\)\(/debian-installer/\)\2\(/initrd\)\(\.gz\)\$!if [ \! -e \"\1\2\6-\4\7\" ] ; then mkdir -p \1\2 \&\& mv -i \1\2\3\4\5\2\6\7 \1\2\6-\4\7 ; else echo duplicate; fi!e" \
		-e "s!^\(${version}-${release}"''"/\)\([^/]*\)\(/tmp/\)\(txt/\|gtk/\)\(debian-installer/\)\2\(/[^/]*\)\$!if [ -L \1\2\3\4\5\2\6 ] ; then rm \1\2\3\4\5\2\6 ; elif [ \! -e \"\1\2\6\" ] ; then mkdir -p \1\2 \&\& mv -it \1\2 \1\2\3\4\5\2\6 ; elif diff -u \1\2\6 \1\2\3\4\5\2\6 ; then rm \1\2\3\4\5\2\6 ; fi!e" \
		-e "s!^\(${version}-${release}"''"/\)\([^/]*\)\(/tmp/\)\(txt/\|gtk/\)\(debian-installer/\)\2!\1 # \2 # \3 # \4 # \5 # !" \
		-e "s!^\(${version}-${release}"''"/\)\([^/]*\)\(/tmp/\)\(txt\|gtk\)\(/[^/]*\)\$!if [ -L \1\2\3\4\5 ] ; then rm \1\2\3\4\5 ; elif [ \! -e \"\1\2\5\" ] ; then mkdir -p \1\2 \&\& mv -it \1\2 \1\2\3\4\5 ; elif diff -u \1\2\5 \1\2\3\4\5 ; then rm \1\2\3\4\5 ; fi!e" \
		-e "s!^\(${version}-${release}"''"/\)\([^/]*\)\(/boot-screens/\)\([^/]*\)\$!if [ -L \1\2\3\4 ] ; then rm \1\2\3\4 ; elif [ \! -e \"\1\3\4\" ] ; then mkdir -p \1\3 \&\& mv -it \1\3 \1\2\3\4 ; elif diff -q \1\3\4 \1\2\3\4 ; then rm \1\2\3\4 ; fi!e" \
		-e "s!^\(${version}-${release}"''"/\)\([^/]*\)\(/grub/\)\([^/]*\)\$!if [ -L \1\2\3\4 ] ; then rm \1\2\3\4 ; elif [ \! -e \"\1\3\4\" ] ; then mkdir -p \1\3 \&\& mv -it \1\3 \1\2\3\4 ; elif diff -q \1\3\4 \1\2\3\4 ; then rm \1\2\3\4 ; fi!e" \
		-e '/^$/d' |\
	sed -zr \
		-e "s!^(${version}-${release}"'/)([^/]*)(/grub/[x864_]*-efi/)([^/]*)$!if [ -L "&" ] ; then rm "&" ; elif [ \! -e "&" ] ; then mkdir -p \1\3 \&\& mv -it \1\3 "&" ; elif diff -q \1\3\4 "&" ; then rm "&" ; fi!e' \
		-e "s!^(${version}-${release}/)([^/]*/)(version.info|pxelinux.0|grub2pxe|grub.cfg|splash.png|font.pf2)"'$!if [ \! -e "&" ] ; then mkdir -p \1 \&\& mv -it \1 "&" ; elif diff -q \1\3 "&" ; then rm "&" ; fi!e' \
		-e "\!^${version}-${release}/boot-screens/!d" \
		-e "\!^${version}-${release}/grub/!d" \
		-e "\!^${version}-${release}"'/[^/]*/(linux|initrd-...\.gz|kfreebsd-10.gz)$!d' \
		-e "\!^${version}-${release}"'/(version.info|splash.png|pxelinux.0)$!d' \
		-e '/^$/d' | xargs -0rn1 \
	&& echo ok

	[ -d debian-installer 	     ] && find debian-installer	       -depth -type d -print0|xargs -0r rmdir --ignore-fail-on-non-empty
	[ -d "${version}-${release}" ] && find "${version}-${release}" -depth -type d -print0|xargs -0r rmdir --ignore-fail-on-non-empty
}

function do_version () {
	local mirror
	local release
	local version

	mirror="$1";shift
	release="$1";shift

	for version ; do
		echo download "${mirror}" "${release}" "${version}" i386 amd64
		download "${mirror}" "${release}" "${version}" i386 amd64
		# kfreebsd dropped in jessie - oldstable
		false && download "${mirror}" "${release}" "${version}" kfreebsd-i386 kfreebsd-amd64
		# powerpc dropped in stretch - stable
		false && download "${mirror}" "${release}" "${version}" powerpc

		echo move "${release}" "${version}"
		move "${release}" "${version}"
	done
}

function do_release {
	local mirror
	local release

	mirror="$1";shift

	for release ; do
		case "${release}" in
			*/*)

				echo do_version "${mirror}" "${release%/*}" "${release##*/}"
				do_version "${mirror}" "${release%/*}" "${release#*/}"
				;;
			*)
				echo do_version "${mirror}" "${release}" "current"
				do_version "${mirror}" "${release}" "current"
				;;
		esac
	done
}
dist=debian
case "${dist}" in
	debian)
		cc=us
		#mirror="http://ftp.${cc}.debian.org/debian"
		mirror="http://mirrors.wikimedia.org/debian"
		;;
	devuan)
		#mirror="http://deb.devuan.org/merged"
		#mirror="http://devuanfwojg73k6r.onion/merged"
		mirror="https://sledjhamr.org/devuan/devuan"
		;;
	ubuntu)
		mirror="http://archive.ubuntu.com/ubuntu"
		;;
esac

do_release "${mirror}" stable jessie
#do_release "${mirror}" testing stable oldstable oldoldstable

# bs_test
# grub
ls $S_OPTIONS -F
